name: Build and Release .NET 9 API and Electron UI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        working-directory: app-ui
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check dotnet location and version
        run: |
          which dotnet
          dotnet --info

      - name: Clean .NET tools cache
        run: dotnet nuget locals all --clear

      # --- Run NUnit Tests (before build) ---
      # --- macOS agents are run on Apple Silicon CPUS! ---
      - name: Run Unit Tests (macOS)
        if: runner.os == 'macOS'
        working-directory: app-api
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --arch arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run Unit Tests (Windows, Linux)
        if: runner.os != 'macOS'
        working-directory: app-api
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build (Windows)
        if: runner.os == 'Windows'
        working-directory: app-ui
        run: npm run buildwin
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build (macOS x64)
        if: runner.os == 'macOS'
        working-directory: app-ui
        run: npm run buildmac-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build (macOS arm64)
        if: runner.os == 'macOS'
        working-directory: app-ui
        run: npm run buildmac-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build (Linux x64)
        if: runner.os == 'Linux'
        working-directory: app-ui
        run: npm run buildlinux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Zip x64 Mac App (macOS)
        if: runner.os == 'macOS'
        run: |          
          cd app-ui/dist/mac && zip -r ElectronStarterApp-x64.zip ElectronStarterApp.app
        shell: bash

      - name: Zip arm64 Mac App (macOS)
        if: runner.os == 'macOS'
        run: |
          cd app-ui/dist/mac-arm64 && zip -r ElectronStarterApp-arm64.zip ElectronStarterApp.app
        shell: bash

      - name: Zip win-unpacked directory (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path app-ui/dist/win-unpacked/* -DestinationPath app-ui/dist/win-unpacked.zip
        shell: pwsh

      - name: Zip linux-unpacked directory (Linux)
        if: runner.os == 'Linux'
        run: |
          cd app-ui/dist && zip -r linux-unpacked-x64.zip linux-unpacked
        shell: bash

      - name: Upload Electron Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ runner.os }}
          path: |
            app-ui/dist/mac/*.zip
            app-ui/dist/mac-arm64/*.zip
            app-ui/dist/*.zip
            app-ui/dist/*.dmg
            app-ui/dist/*.exe
            app-ui/dist/*.appimage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: electron-build-Windows
          path: artifacts/windows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: electron-build-macOS
          path: artifacts/macos
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: electron-build-Linux
          path: artifacts/linux
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/windows/**
            artifacts/macos/**
            artifacts/linux/**
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
