name: Build and Release .NET 9 API and Electron UI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        working-directory: app-ui
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build (Windows)
        if: runner.os == 'Windows'
        working-directory: app-ui
        run: npm run buildwin
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build (macOS)
        if: runner.os == 'macOS'
        working-directory: app-ui
        run: npm run buildmacdev
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build (Linux)
        if: runner.os == 'Linux'
        working-directory: app-ui
        run: npm run buildlinux
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}          

      - name: Upload Electron Artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ runner.os }}
          path: |
            app-ui/dist/mac/*.app
            app-ui/dist/win-unpacked/**
            app-ui/dist/linux-unpacked/**
            app-ui/dist/*.dmg
            app-ui/dist/*.exe
            app-ui/dist/*.appimage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: electron-build-Windows
          path: artifacts/windows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: electron-build-macOS
          path: artifacts/macos
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: electron-build-Linux
          path: artifacts/linux
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}          

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/windows/**
            artifacts/macos/**
            artifacts/linux/**
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
